package com.wivernz.itera.domain.training

import com.wivernz.itera.domain.model.ActivitySource
import com.wivernz.itera.domain.model.ActivityState
import com.wivernz.itera.domain.model.Curriculum
import com.wivernz.itera.domain.model.DayPart
import com.wivernz.itera.domain.model.ExerciseType
import com.wivernz.itera.domain.model.MasteryLevel
import com.wivernz.itera.domain.model.ProgramPace
import com.wivernz.itera.domain.model.ReviewItem
import com.wivernz.itera.domain.model.Skill
import com.wivernz.itera.domain.model.Technique
import com.wivernz.itera.domain.model.TechniqueId
import com.wivernz.itera.domain.model.TimeBudget
import com.wivernz.itera.domain.model.UserPreferences
import com.wivernz.itera.domain.repository.PlannedActivity
import java.time.LocalDate
import java.time.LocalTime

/** Bumped whenever generation changes, so stored days are never regenerated by a different engine (section 5). */
const val GENERATOR_VERSION = 1

/** A surfaced review lasts five minutes ("Due today - 5 min - from Day 6"). */
const val REVIEW_MINUTES = 5

data class DueReview(val item: ReviewItem, val sourceProgramDay: Int?)

/** Everything plan generation depends on. Identical inputs produce identical plans (ADR-0011). */
data class PlanInputs(
    val programDay: Int,
    val curriculum: Curriculum,
    val catalog: List<Technique>,
    // after this day's unlock step
    val unlocked: Set<TechniqueId>,
    // in due order (ReviewScheduler.dueOn)
    val dueReviews: List<DueReview>,
    val preferences: UserPreferences,
    val mastery: Map<TechniqueId, MasteryLevel>,
    val lastUsedOn: Map<TechniqueId, LocalDate>
)

data class ComposedPlan(
    // ordered by orderIndex; combination steps follow their parent
    val activities: List<PlannedActivity>,
    val weeklyLookBack: Boolean,
    val combinationDay: Boolean
)

/**
 * The pure part of `GenerateDailyPlanUseCase`: docs/engine/01-training-plan-engine.md sections 3-8.
 * No randomness and no clock; every choice has an explicit, total tiebreak.
 */
object PlanComposer {
    val REFLECTION: TechniqueId = TechniqueId("daily_reflection")
    val POMODORO: TechniqueId = TechniqueId("pomodoro")
    val DEEP_WORK: TechniqueId = TechniqueId("deep_work")

    fun reviewCap(pace: ProgramPace, budget: TimeBudget): Int {
        val base = when (pace) {
            ProgramPace.GENTLE -> 1
            ProgramPace.STANDARD -> 2
            ProgramPace.INTENSE -> 3
        }
        return base + if (budget == TimeBudget.LONG) 1 else 0
    }

    /** Section 3.2. */
    fun focusSuggestionAllowed(
        unlocked: Set<TechniqueId>,
        budget: TimeBudget,
        combinationDay: Boolean
    ): Boolean = (POMODORO in unlocked || DEEP_WORK in unlocked) && budget != TimeBudget.SHORT &&
        !combinationDay

    /** Deep Work once unlocked and the budget is long or the pace intense (docs/prd/07 section 5); else Pomodoro. */
    fun focusTechnique(unlocked: Set<TechniqueId>, preferences: UserPreferences): TechniqueId =
        if (DEEP_WORK in unlocked &&
            (preferences.timeBudget == TimeBudget.LONG || preferences.pace == ProgramPace.INTENSE)
        ) {
            DEEP_WORK
        } else {
            POMODORO
        }

    /**
     * Section 3.3, "Keep using": lowest non-NONE mastery, then oldest last use, then focus-area membership,
     * then lowest intro day, then id. Excludes [exclude], the reflection, retired, locked and INTEGRATED.
     */
    fun practiceTechnique(inputs: PlanInputs, exclude: Set<TechniqueId>): Technique? =
        inputs.catalog.filter {
            it.id in inputs.unlocked &&
                !it.retired &&
                it.id != REFLECTION &&
                it.id !in exclude &&
                levelOf(inputs, it.id) in PRACTICE_LEVELS
        }.sortedWith(
            compareBy<Technique>(
                { levelOf(inputs, it.id).ordinal },
                { inputs.lastUsedOn[it.id] ?: LocalDate.MIN },
                { if (it.skill in inputs.preferences.focusAreas) 0 else 1 },
                { it.introDay ?: 0 },
                { it.id.value }
            )
        ).firstOrNull()

    /**
     * Section 7.1: one technique at PRACTICED or better from each slot, Planning -> Focus/Learning ->
     * Reflection, preferring focus areas, then the lowest intro day. Null when a slot cannot be filled.
     */
    fun generatedCombination(inputs: PlanInputs): List<Technique>? {
        val eligible = inputs.catalog.filter {
            it.id in inputs.unlocked && !it.retired && levelOf(inputs, it.id) in COMBINATION_LEVELS
        }
        val order = compareBy<Technique>(
            { if (it.skill in inputs.preferences.focusAreas) 0 else 1 },
            { it.introDay ?: 0 },
            { it.id.value }
        )
        val slots = listOf(
            setOf(Skill.PLANNING),
            setOf(Skill.FOCUS, Skill.LEARNING),
            setOf(Skill.REFLECTION)
        )
        return slots.map { skills ->
            eligible.filter { it.skill in skills }.sortedWith(order).firstOrNull() ?: return null
        }
    }

    fun compose(inputs: PlanInputs): ComposedPlan {
        val prefs = inputs.preferences
        val byId = inputs.catalog.associateBy { it.id }
        val curriculumDay = inputs.curriculum.days.getOrNull(inputs.programDay - 1)
        val pastCurriculum = inputs.programDay > inputs.curriculum.days.size
        val entries = mutableListOf<Entry>()

        // 6. PRIMARY
        var combinationSteps: List<Technique>? = null
        var programTechnique: Technique? = null
        var newTechnique: TechniqueId? = null
        var curriculumCombination: Int? = null
        if (curriculumDay != null && curriculumDay.combination.isNotEmpty()) {
            combinationSteps = curriculumDay.combination.mapNotNull { byId[it.techniqueId] }
                .filter { !it.retired && it.id in inputs.unlocked }
            curriculumCombination = curriculumDay.day
        } else if (curriculumDay?.newTechniqueId != null &&
            byId[curriculumDay.newTechniqueId]?.retired == false
        ) {
            programTechnique = byId.getValue(curriculumDay.newTechniqueId)
            newTechnique = programTechnique.id
        } else if (pastCurriculum &&
            (inputs.programDay - inputs.curriculum.days.size) % COMBINATION_EVERY == 0
        ) {
            combinationSteps = generatedCombination(inputs)
        }
        if (combinationSteps == null || combinationSteps.isEmpty()) {
            combinationSteps = null
            if (programTechnique == null) {
                programTechnique =
                    practiceTechnique(inputs, emptySet()) ?: fallbackTechnique(inputs)
            }
        }
        if (combinationSteps != null) {
            entries += combination(combinationSteps, curriculumCombination, prefs)
        } else if (programTechnique != null) {
            entries += Entry(
                activity(
                    programTechnique.id,
                    programTechnique.exerciseType,
                    ActivitySource.PROGRAM,
                    DayPart.MORNING,
                    "activity_program",
                    linkedMapOf(
                        "technique" to programTechnique.id.value,
                        "minutes" to programTechnique.estimatedMinutes
                    ),
                    programTechnique.estimatedMinutes,
                    optional = false,
                    scheduledAt = prefs.morningTime
                )
            )
        }

        // 7. REVIEWS
        val reviews = inputs.dueReviews
            .filter { it.item.techniqueId in inputs.unlocked }
            .take(reviewCap(prefs.pace, prefs.timeBudget))
        reviews.forEach { due ->
            val args = linkedMapOf<String, Any>(
                "technique" to due.item.techniqueId.value,
                "minutes" to REVIEW_MINUTES
            )
            due.sourceProgramDay?.let { args["sourceDay"] = it }
            entries += Entry(
                activity(
                    due.item.techniqueId,
                    ExerciseType.REVIEW,
                    ActivitySource.REVIEW,
                    DayPart.MORNING,
                    "activity_review",
                    args,
                    REVIEW_MINUTES,
                    optional = false,
                    scheduledAt = prefs.morningTime,
                    reviewItemId = due.item.id
                )
            )
        }

        // 8. SECONDARY: at most one optional activity, displaced by a due review, never on a combination day
        if (combinationSteps == null && reviews.isEmpty()) {
            val inPlan = entries.map { it.activity.techniqueId }.toSet()
            val programIsFocusBlock = programTechnique?.skill == Skill.FOCUS &&
                programTechnique.exerciseType == ExerciseType.FOCUS_TIMER
            val daytime = daytimeTime(prefs.morningTime)
            val focusUnlocked = POMODORO in inputs.unlocked || DEEP_WORK in inputs.unlocked
            val secondary = when {
                programIsFocusBlock -> null
                focusSuggestionAllowed(inputs.unlocked, prefs.timeBudget, false) ->
                    byId[focusTechnique(inputs.unlocked, prefs)]?.let {
                        focus(it, "activity_focus", daytime)
                    }
                // Day 1: a generic 25-minute block attached to Pomodoro that does not grant its mastery
                !focusUnlocked && prefs.timeBudget != TimeBudget.SHORT ->
                    byId[POMODORO]?.let { focus(it, "activity_focus_generic", daytime) }
                else -> null
            } ?: practiceTechnique(inputs, inPlan + listOfNotNull(newTechnique))?.let {
                practicePrompt(it, daytime)
            }
            secondary?.let { entries += Entry(it) }
        }

        // 9. REFLECTION, always last
        val weeklyLookBack = curriculumDay?.weeklyLookBack
            ?: (inputs.programDay % WEEK_LENGTH == 0)
        val reflectionArgs = linkedMapOf<String, Any>(
            "technique" to REFLECTION.value,
            "minutes" to (byId[REFLECTION]?.estimatedMinutes ?: 2),
            "eveningTime" to prefs.eveningTime.toString()
        )
        if (weeklyLookBack) reflectionArgs["weeklyLookBack"] = true
        entries += Entry(
            activity(
                REFLECTION,
                ExerciseType.REFLECTION,
                ActivitySource.REFLECTION,
                DayPart.EVENING,
                "activity_reflection",
                reflectionArgs,
                byId[REFLECTION]?.estimatedMinutes ?: 2,
                optional = false,
                scheduledAt = prefs.eveningTime
            )
        )

        // 10. orderIndex by (dayPart, source priority, insertion order); steps directly after their parent
        val ordered = entries.withIndex()
            .sortedWith(
                compareBy(
                    { it.value.activity.dayPart.ordinal },
                    { SOURCE_PRIORITY.getValue(it.value.activity.source) },
                    { it.index }
                )
            )
            .flatMap { listOf(it.value.activity) + it.value.children }
            .mapIndexed { index, activity -> activity.copy(orderIndex = index) }
        return ComposedPlan(ordered, weeklyLookBack, combinationSteps != null)
    }

    private fun combination(
        steps: List<Technique>,
        curriculumDay: Int?,
        prefs: UserPreferences
    ): Entry {
        // The reflection step is folded into the evening reflection (section 4, Day 14): it gets no row.
        val children = steps.filter { it.id != REFLECTION }.mapIndexed { index, technique ->
            val minutes = technique.defaults.focusMinutes ?: technique.estimatedMinutes
            activity(
                technique.id,
                technique.exerciseType,
                ActivitySource.COMBINATION,
                DayPart.MORNING,
                "activity_program",
                linkedMapOf(
                    "technique" to technique.id.value,
                    "minutes" to minutes,
                    "step" to index + 1
                ),
                minutes,
                optional = false,
                scheduledAt = prefs.morningTime
            )
        }
        val total = children.sumOf { it.estimatedMinutes }
        val args = linkedMapOf<String, Any>(
            "minutes" to total,
            "steps" to steps.joinToString(",") { it.id.value }
        )
        curriculumDay?.let { args["curriculumDay"] = it }
        val parent = activity(
            steps.first().id,
            ExerciseType.COMBINATION,
            ActivitySource.COMBINATION,
            DayPart.MORNING,
            "activity_combination",
            args,
            total,
            optional = false,
            scheduledAt = prefs.morningTime
        )
        return Entry(parent, children)
    }

    private fun focus(technique: Technique, copyKey: String, at: LocalTime): PlannedActivity {
        val minutes = technique.defaults.focusMinutes ?: technique.estimatedMinutes
        return activity(
            technique.id,
            ExerciseType.FOCUS_TIMER,
            ActivitySource.FOCUS_SUGGESTION,
            DayPart.DAYTIME,
            copyKey,
            linkedMapOf(
                "technique" to technique.id.value,
                "minutes" to minutes,
                "time" to at.toString()
            ),
            minutes,
            optional = true,
            scheduledAt = at
        )
    }

    /** "Tap to log when you use it": a TEMPLATE activity completed with the `always` rule. */
    private fun practicePrompt(technique: Technique, at: LocalTime) = activity(
        technique.id,
        ExerciseType.TEMPLATE,
        ActivitySource.PRACTICE_PROMPT,
        DayPart.DAYTIME,
        "activity_practice",
        linkedMapOf("technique" to technique.id.value),
        technique.estimatedMinutes,
        optional = true,
        scheduledAt = at
    )

    private fun activity(
        techniqueId: TechniqueId,
        exerciseType: ExerciseType,
        source: ActivitySource,
        dayPart: DayPart,
        copyKey: String,
        copyArgs: Map<String, Any>,
        minutes: Int,
        optional: Boolean,
        scheduledAt: LocalTime?,
        reviewItemId: Long? = null
    ) = PlannedActivity(
        techniqueId = techniqueId,
        exerciseType = exerciseType,
        source = source,
        dayPart = dayPart,
        orderIndex = 0,
        copyKey = copyKey,
        copyArgs = copyArgs,
        estimatedMinutes = minutes,
        optional = optional,
        // MORNING is reachable from 00:00; later parts become AVAILABLE through the Reach transition
        state = if (dayPart ==
            DayPart.MORNING
        ) {
            ActivityState.AVAILABLE
        } else {
            ActivityState.SCHEDULED
        },
        scheduledAt = scheduledAt,
        reviewItemId = reviewItemId
    )

    /** Past the curriculum with nothing below INTEGRATED: the least recently used unlocked technique. */
    private fun fallbackTechnique(inputs: PlanInputs): Technique? = inputs.catalog.filter {
        it.id in inputs.unlocked && !it.retired && it.id != REFLECTION
    }.sortedWith(
        compareBy<Technique>(
            { inputs.lastUsedOn[it.id] ?: LocalDate.MIN },
            { it.introDay ?: 0 },
            { it.id.value }
        )
    ).firstOrNull()

    private fun levelOf(inputs: PlanInputs, id: TechniqueId) =
        inputs.mastery[id] ?: MasteryLevel.NONE

    private class Entry(
        val activity: PlannedActivity,
        val children: List<PlannedActivity> = emptyList()
    )

    private const val COMBINATION_EVERY = 3
    private const val WEEK_LENGTH = 7
    private val PRACTICE_LEVELS =
        setOf(MasteryLevel.MET, MasteryLevel.PRACTICED, MasteryLevel.APPLIED)
    private val COMBINATION_LEVELS =
        setOf(MasteryLevel.PRACTICED, MasteryLevel.APPLIED, MasteryLevel.INTEGRATED)
    private val SOURCE_PRIORITY = mapOf(
        ActivitySource.PROGRAM to 0,
        ActivitySource.COMBINATION to 0,
        ActivitySource.REVIEW to 1,
        ActivitySource.FOCUS_SUGGESTION to 2,
        ActivitySource.PRACTICE_PROMPT to 3,
        ActivitySource.MANUAL to 4,
        ActivitySource.REFLECTION to 5
    )
}
