package com.wivernz.itera.analytics
import com.wivernz.itera.domain.model.ActivitySource
import com.wivernz.itera.domain.model.ExerciseType
import com.wivernz.itera.domain.model.MasteryLevel
import com.wivernz.itera.domain.model.RecallGrade
import com.wivernz.itera.domain.model.Skill
import com.wivernz.itera.domain.model.SkillLevel
import com.wivernz.itera.domain.model.TimeBudget
import com.wivernz.itera.domain.model.TrainingDayStatus
import org.junit.Assert.assertEquals
import org.junit.Assert.assertThrows
import org.junit.Assert.assertTrue
import org.junit.Test
class EventCatalogueTest {
    @Test fun namesAndKeysMatchContract() {
        val cases = listOf(
            Triple(Event.OnboardingStarted, "onboarding_started", setOf()),
            Triple(
                Event.OnboardingStepCompleted(1),
                "onboarding_step_completed",
                setOf("step")
            ),
            Triple(
                Event.OnboardingCompleted(
                    1,
                    TimeBudget.STANDARD,
                    1,
                    1,
                    true
                ),
                "onboarding_completed",
                setOf(
                    "focusAreaCount",
                    "timeBudget",
                    "morningHour",
                    "eveningHour",
                    "notificationsGranted"
                )
            ),
            Triple(
                Event.PlanGenerated(
                    1,
                    1,
                    1,
                    true,
                    1
                ),
                "plan_generated",
                setOf(
                    "programDay",
                    "activityCount",
                    "reviewCount",
                    "hasCombination",
                    "generatorVersion"
                )
            ),
            Triple(
                Event.DayRolledOver(
                    TrainingDayStatus.COMPLETE,
                    1
                ),
                "day_rolled_over",
                setOf(
                    "previousStatus",
                    "expiredCount"
                )
            ),
            Triple(
                Event.DayCompleted(
                    1,
                    1,
                    1,
                    1
                ),
                "day_completed",
                setOf(
                    "programDay",
                    "completedCount",
                    "skippedCount",
                    "durationMinutes"
                )
            ),
            Triple(
                Event.ProgramDayAdvanced(
                    1,
                    1
                ),
                "program_day_advanced",
                setOf(
                    "from",
                    "to"
                )
            ),
            Triple(
                Event.ExerciseOpened(
                    AnalyticsTechnique.POMODORO,
                    ExerciseType.TEMPLATE,
                    ActivitySource.PROGRAM
                ),
                "exercise_opened",
                setOf(
                    "techniqueId",
                    "exerciseType",
                    "source"
                )
            ),
            Triple(
                Event.ExerciseStarted(
                    AnalyticsTechnique.POMODORO,
                    ExerciseType.TEMPLATE
                ),
                "exercise_started",
                setOf(
                    "techniqueId",
                    "exerciseType"
                )
            ),
            Triple(
                Event.ExerciseCompleted(
                    AnalyticsTechnique.POMODORO,
                    ExerciseType.TEMPLATE,
                    ActivitySource.PROGRAM,
                    1,
                    null,
                    true
                ),
                "exercise_completed",
                setOf(
                    "techniqueId",
                    "exerciseType",
                    "source",
                    "durationSeconds",
                    "difficulty",
                    "hasNote"
                )
            ),
            Triple(
                Event.ExerciseSnoozed(
                    AnalyticsTechnique.POMODORO,
                    1
                ),
                "exercise_snoozed",
                setOf(
                    "techniqueId",
                    "minutesDeferred"
                )
            ),
            Triple(
                Event.ExerciseSkipped(
                    AnalyticsTechnique.POMODORO,
                    ExerciseType.TEMPLATE
                ),
                "exercise_skipped",
                setOf(
                    "techniqueId",
                    "exerciseType"
                )
            ),
            Triple(
                Event.ExerciseAbandoned(
                    AnalyticsTechnique.POMODORO,
                    1
                ),
                "exercise_abandoned",
                setOf(
                    "techniqueId",
                    "secondsSpent"
                )
            ),
            Triple(
                Event.PracticeLogged(AnalyticsTechnique.POMODORO),
                "practice_logged",
                setOf("techniqueId")
            ),
            Triple(
                Event.FocusStarted(
                    AnalyticsTechnique.POMODORO,
                    1
                ),
                "focus_started",
                setOf(
                    "techniqueId",
                    "plannedMinutes"
                )
            ),
            Triple(Event.FocusPaused(1), "focus_paused", setOf("remainingSeconds")),
            Triple(
                Event.FocusExtended(
                    1,
                    1
                ),
                "focus_extended",
                setOf(
                    "addedSeconds",
                    "timesExtended"
                )
            ),
            Triple(
                Event.FocusCompleted(
                    1,
                    1,
                    true
                ),
                "focus_completed",
                setOf(
                    "plannedSeconds",
                    "actualSeconds",
                    "completedNaturally"
                )
            ),
            Triple(
                Event.FocusRestored(
                    1,
                    true
                ),
                "focus_restored",
                setOf(
                    "remainingSeconds",
                    "afterProcessDeath"
                )
            ),
            Triple(
                Event.ReviewDue(
                    AnalyticsTechnique.POMODORO,
                    1,
                    1
                ),
                "review_due",
                setOf(
                    "techniqueId",
                    "stageIndex",
                    "daysOverdue"
                )
            ),
            Triple(
                Event.ReviewOpened(
                    AnalyticsTechnique.POMODORO,
                    1
                ),
                "review_opened",
                setOf(
                    "techniqueId",
                    "stageIndex"
                )
            ),
            Triple(
                Event.ReviewRevealed(
                    AnalyticsTechnique.POMODORO,
                    1
                ),
                "review_revealed",
                setOf(
                    "techniqueId",
                    "stageIndex"
                )
            ),
            Triple(
                Event.ReviewGraded(
                    AnalyticsTechnique.POMODORO,
                    1,
                    1,
                    RecallGrade.SOLID
                ),
                "review_graded",
                setOf(
                    "techniqueId",
                    "stageBefore",
                    "stageAfter",
                    "grade"
                )
            ),
            Triple(
                Event.TechniqueUnlocked(
                    AnalyticsTechnique.POMODORO,
                    1
                ),
                "technique_unlocked",
                setOf(
                    "techniqueId",
                    "programDay"
                )
            ),
            Triple(
                Event.MasteryChanged(
                    AnalyticsTechnique.POMODORO,
                    MasteryLevel.MET,
                    MasteryLevel.MET
                ),
                "mastery_changed",
                setOf(
                    "techniqueId",
                    "from",
                    "to"
                )
            ),
            Triple(
                Event.SkillLevelChanged(
                    Skill.FOCUS,
                    SkillLevel.STARTING,
                    SkillLevel.STARTING
                ),
                "skill_level_changed",
                setOf(
                    "skill",
                    "from",
                    "to"
                )
            ),
            Triple(
                Event.ScreenViewed(ScreenRoute.TODAY),
                "screen_viewed",
                setOf("route")
            ),
            Triple(
                Event.SettingChanged(
                    SettingKey.MORNING_TIME,
                    SettingValue.Hour(8)
                ),
                "setting_changed",
                setOf(
                    "key",
                    "value"
                )
            ),
            Triple(
                Event.ResetPerformed(ResetTier.PROGRAM),
                "reset_performed",
                setOf("tier")
            ),
            Triple(
                Event.JournalExported(
                    ExportRange.ALL,
                    1,
                    1L
                ),
                "journal_exported",
                setOf(
                    "range",
                    "dayCount",
                    "sizeBytes"
                )
            ),
            Triple(
                Event.NotificationScheduled(
                    NotificationType.MORNING,
                    1
                ),
                "notification_scheduled",
                setOf(
                    "type",
                    "delayMinutes"
                )
            ),
            Triple(
                Event.NotificationPosted(NotificationType.MORNING),
                "notification_posted",
                setOf("type")
            ),
            Triple(
                Event.NotificationSuppressed(
                    NotificationType.MORNING,
                    SuppressionReason.DISABLED
                ),
                "notification_suppressed",
                setOf(
                    "type",
                    "reason"
                )
            ),
            Triple(
                Event.NotificationOpened(NotificationType.MORNING),
                "notification_opened",
                setOf("type")
            )
        )
        assertEquals(34, cases.size)
        cases.forEach {
                (
                    event,
                    name,
                    keys
                ) ->
            assertEquals(
                name,
                event.name
            )
            assertEquals(
                keys,
                event.params.keys
            )
            assertTrue(
                event.params.values.all {
                    it == null || it is String || it is Number || it is Boolean
                }
            )
        }
        assertEquals("Today", Event.ScreenViewed(ScreenRoute.TODAY).params["route"])
        assertEquals(
            8,
            Event.SettingChanged(
                SettingKey.MORNING_TIME,
                SettingValue.Hour(8)
            ).params["value"]
        )
        assertThrows(IllegalArgumentException::class.java) { SettingValue.Hour(24) }
    }
}
